<?php

return [
    'default_country' => env('OPFIN_DEFAULT_COUNTRY', 'UG'),

    'integrations' => [
        // auto = prefer Cito when configured, otherwise use the direct adapter. A failed
        // or ambiguous Cito call never silently triggers a second paid provider request.
        'external_service_route' => env('OPFIN_EXTERNAL_SERVICE_ROUTE', 'auto'),
        'direct_provider_fallback_enabled' => (bool) env('OPFIN_DIRECT_PROVIDER_FALLBACK_ENABLED', true),
        'silent_failover_enabled' => false,
    ],

    'credit' => [
        'max_debt_service_ratio_percent' => (float) env('OPFIN_MAX_DSR_PERCENT', 35),
        'affordability_formula' => 'estimated_monthly_obligation_minor / verified_monthly_income_minor * 100',
        'legacy_origination_enabled' => (bool) env('OPFIN_ENABLE_LEGACY_LOAN_ORIGINATION', false),
        'model_version' => env('OPFIN_CREDIT_MODEL_VERSION', 'composite-v1'),
        'auto_decision_policy_version' => env('OPFIN_AUTO_DECISION_POLICY_VERSION', 'credit-profile-v1'),
        'minimum_limit_coverage_percent' => (float) env('OPFIN_MIN_LIMIT_COVERAGE_PERCENT', 60),
        'scoring_weights' => [
            'crb' => 40,
            'mno' => 25,
            'third_party' => 15,
            'internal' => 20,
        ],
        'positive_employment_behaviour' => [
            'max_uplift_points' => (float) env('OPFIN_EMPLOYMENT_BEHAVIOUR_MAX_UPLIFT', 5),
            'signals' => [
                'attendance_reliability' => 1.0,
                'positive_performance' => 1.5,
                'employment_progression' => 1.0,
                'recognition' => 0.5,
                'workplace_reliability' => 1.0,
            ],
        ],
        'limit_bands' => [
            'Very strong' => ['min_score' => 85, 'limit_minor' => 500000],
            'Strong' => ['min_score' => 75, 'limit_minor' => 350000],
            'Good' => ['min_score' => 65, 'limit_minor' => 200000],
            'Building' => ['min_score' => 55, 'limit_minor' => 100000],
            'Starting' => ['min_score' => 45, 'limit_minor' => 50000],
            'Not eligible' => ['min_score' => 0, 'limit_minor' => 0],
        ],
        'default_pricing' => [
            'access_fee_percent' => (float) env('OPFIN_ACCESS_FEE_PERCENT', 3),
            'disbursement_fee_minor' => (int) env('OPFIN_DISBURSEMENT_FEE_MINOR', 2000),
            'fee_treatment' => env('OPFIN_FEE_TREATMENT', 'financed'),
            'expires_in_minutes' => (int) env('OPFIN_OFFER_EXPIRY_MINUTES', 1440),
        ],
    ],

    'regulatory' => [
        'licence_class' => env('OPFIN_REGULATORY_LICENCE_CLASS', ''),
        'jurisdiction_country' => env('OPFIN_REGULATORY_COUNTRY', env('OPFIN_DEFAULT_COUNTRY', 'UG')),
        'credit_reporting_due_days' => (int) env('UMRA_CREDIT_REPORTING_DUE_DAYS', 30),
        'complaint_resolution_days' => (int) env('UMRA_COMPLAINT_RESOLUTION_DAYS', 30),
        'enforce_umra_npl_cap' => (bool) env('UMRA_ENFORCE_NPL_CAP', true),
        'licensed_entity_name' => env('OPFIN_LICENSED_ENTITY_NAME'),
        'licensed_trading_name' => env('OPFIN_LICENSED_TRADING_NAME', 'OpFin'),
        'umra_license_number' => env('OPFIN_UMRA_LICENSE_NUMBER'),
        'business_address' => env('OPFIN_BUSINESS_ADDRESS'),
        'complaints_email' => env('OPFIN_COMPLAINTS_EMAIL'),
        'complaints_phone' => env('OPFIN_COMPLAINTS_PHONE'),
        'complaints_url' => env('OPFIN_COMPLAINTS_URL'),
    ],

    'accounting' => [
        'fee_recognition_policy_type' => env('OPFIN_FEE_RECOGNITION_POLICY_TYPE', 'credit_fee_recognition'),
        'tax_policy_type' => env('OPFIN_TAX_POLICY_TYPE', 'tax'),
        'efris_enabled' => (bool) env('OPFIN_EFRIS_ENABLED', false),
        'impairment_max_age_days' => (int) env('OPFIN_IMPAIRMENT_MAX_AGE_DAYS', 31),
    ],

    'customer_experience' => [
        'secondary_phone_required' => false,
        'simple_language_default' => true,
        'minimum_tap_target_dp' => 48,
        'support_screen_readers' => true,
        'support_dynamic_text' => true,
        'reduced_motion_respected' => true,
    ],

    'capabilities' => [
        'home' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'activation' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'identity' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'kyc' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'identity_provider_credentials_and_certification'],
        'consent' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'financial_passport' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'support' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'security_centre' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'borrow' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'licensed_product_and_funding_configuration'],
        'essentials' => [
            'status' => 'AVAILABLE',
            'owner' => 'opfin',
            'external_gate' => 'third_party_lender_biller_cpay_cito_and_beneficiary_activation',
        ],
        'budgeting' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'financial_calendar' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'money_autopilot' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'provider_mandates_for_automatic_money_movement'],
        'credit_builder' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'financial_shock_centre' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'save' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'licensed_savings_partner_products'],
        'savings_partner_products' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'partner_product_activation'],
        'savings_contributions' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'governed_payment_route_and_partner_confirmation'],
        'savings_withdrawals' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'partner_withdrawal_and_governed_payment_route'],
        'insurance' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Protection & Asset Plans',
            'member_term' => 'Protection Plans',
            'external_gate' => 'licensed_insurer_underwriter_products',
        ],
        'protection_enrollment' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'insurer_issuance'],
        'protection_premiums' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'governed_payment_route_and_insurer_confirmation'],
        'protection_claims' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'insurer_claim_adjudication'],
        'investments' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'licensed_investment_provider_custody_and_settlement'],
        'household_finance' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'microbusiness' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'asset_finance' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Protection & Asset Plans',
            'member_term' => 'Asset Plans',
            'external_gate' => 'asset_supplier_and_finance_product_activation',
        ],
        'p2p_participatory_finance' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Community Growth Circles',
            'member_term' => 'Growth Circles',
            'external_gate' => 'community_growth_circle_governance_custody_regulatory_signoff',
        ],
        'community_growth_circles' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Community Growth Circles',
            'member_term' => 'Growth Circles',
            'external_gate' => 'community_growth_circle_governance_custody_regulatory_signoff',
        ],
        'workplace_support_finance' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Workplace Support Finance',
            'member_term' => 'Workplace Finance',
            'external_gate' => 'employer_mou_payroll_consent_and_deduction_file_signoff',
        ],
        'member_growth_score' => [
            'status' => 'READY_FOR_INTERNAL_USE',
            'owner' => 'opfin',
            'public_name' => 'Member Growth Score',
            'member_term' => 'Growth Score',
            'external_gate' => 'score_policy_approval_and_adverse_action_disclosure_review',
        ],
        'member_cooperative_core' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Member Cooperative Core',
            'member_term' => 'Cooperative Core',
            'external_gate' => 'sacco_entity_partner_or_membership_model_signoff',
        ],
        'rewards_referrals' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'linked_accounts' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'provider_open_api_or_authorised_data_connection'],
        'whatsapp' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'meta_whatsapp_production_credentials'],
        'ussd' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'ussd_aggregator_short_code_and_callback_configuration'],
        'offline_aware_mode' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'employer' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Workplace Support Finance',
            'member_term' => 'Workplace Finance',
            'external_gate' => 'employer_payroll_integration_for_live_deductions',
        ],
        'sacco' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Member Cooperative Core',
            'member_term' => 'Cooperative Core',
            'external_gate' => 'institution_integration_and_membership_verification',
        ],
        'capital' => [
            'status' => 'DORMANT_READY',
            'owner' => 'opfin',
            'public_name' => 'Community Growth Circles',
            'member_term' => 'Growth Circles',
            'external_gate' => 'capital_provider_and_regulatory_activation',
        ],
        'partner_distribution' => ['status' => 'AVAILABLE', 'owner' => 'opfin', 'external_gate' => 'partner_due_diligence_contract_and_credentials'],
        'payments' => [
            'status' => 'AVAILABLE',
            'owner' => 'opfin',
            'primary_gateway' => 'cpay_via_cito',
            'fallback' => 'certified_direct_provider_adapter',
        ],
        'payment_reconciliation' => [
            'status' => 'AVAILABLE',
            'owner' => 'opfin',
            'provider_evidence' => 'cpay_or_certified_direct_provider',
        ],
        'product_factory' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'workflow_engine' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'rules_engine' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'platform_autopilot' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'regulatory_reporting' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
        'financial_integrity_audit' => ['status' => 'AVAILABLE', 'owner' => 'opfin'],
    ],

    'countries' => [
        'UG' => [
            'name' => 'Uganda',
            'status' => 'PILOT',
            'currency' => 'UGX',
            'languages' => ['en'],
            'payment_platform' => 'cpay',
            'payment_status' => 'PRODUCTION',
            'payment_primary_route' => 'cito_cpay',
            'payment_fallback_policy' => 'certified_direct_provider_adapter',
        ],
    ],
];
