<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpFin club statement {{ $statement->reference }}</title><link rel="stylesheet" href="/club-accounting/statement.css"></head>
<body>@php($s = $statement->snapshot)<header><p>OPFIN · FINANCIAL SPACE ACCOUNTING</p><h1>{{ $s['space']['name'] }}</h1>
<p>{{ $s['report_type'] === 'member_capital_statement' ? 'Member capital and ownership statement' : 'Club financial accounts' }}</p>
<p>{{ $s['period_start'] }} to {{ $s['period_end'] }} · {{ $s['book']['currency'] }} · {{ $s['book']['ownership_model'] }}</p>
<p>Statement {{ $statement->reference }} · Issued {{ $s['issued_at'] }}</p></header>
<main><section class="notice"><p>{{ $s['basis'] }}</p><p>{{ $s['currency_conversion'] }}</p>
@if(($s['integrity_at_issue']['unposted_cashbook_count_at_least'] ?? 0) > 0)<p><strong>Incomplete classification:</strong> {{ $s['integrity_at_issue']['unposted_cashbook_count_at_least'] }} cashbook items require posting. This is not a reconciled final set of accounts.</p>@endif</section>
<h2>Capital and ownership</h2><div class="table-wrap"><table><thead><tr><th>Member</th><th>Capital</th><th>Ownership micro-units</th><th>Indicative asset share</th></tr></thead><tbody>
@foreach($s['member_positions'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ number_format($row['capital_minor'], 0, '.', ',') }}</td><td>{{ number_format($row['units_micro'], 0, '.', ',') }}</td><td>{{ $row['indicative_net_asset_share_minor'] === null ? 'Not available' : number_format($row['indicative_net_asset_share_minor'], 0, '.', ',') }}</td></tr>@endforeach
</tbody></table></div><p>Ownership scale: {{ $s['book']['unit_scale'] }} micro-units per unit. Amounts are integer minor units in the stated currency; no conversion is implied.</p>
<h2>Member movements</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Event</th><th>Capital change</th><th>Unit change</th><th>Recorded cash flow</th></tr></thead><tbody>
@foreach($s['member_movements'] as $row)<tr><td>{{ $row['business_date'] }}</td><td>{{ str_replace('_', ' ', $row['type']) }}</td><td>{{ number_format($row['capital_delta_minor'], 0, '.', ',') }}</td><td>{{ number_format($row['units_delta_micro'], 0, '.', ',') }}</td><td>{{ number_format($row['cash_flow_minor'], 0, '.', ',') }}</td></tr>@endforeach
</tbody></table></div>
@if(isset($s['trial_balance']))<h2>Trial balance</h2><div class="table-wrap"><table><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>
@foreach($s['trial_balance']['accounts'] as $row)<tr><td>{{ $row['code'] }} · {{ $row['name'] }}</td><td>{{ number_format($row['balance_debit_minor'], 0, '.', ',') }}</td><td>{{ number_format($row['balance_credit_minor'], 0, '.', ',') }}</td></tr>@endforeach
<tr><th>Total</th><th>{{ number_format($s['trial_balance']['total_debits_minor'], 0, '.', ',') }}</th><th>{{ number_format($s['trial_balance']['total_credits_minor'], 0, '.', ',') }}</th></tr></tbody></table></div>
<h2>Financial position</h2><dl>@foreach($s['balance_sheet'] as $key => $value)<dt>{{ str_replace('_minor', '', str_replace('_', ' ', $key)) }}</dt><dd>{{ number_format($value, 0, '.', ',') }}</dd>@endforeach</dl>
<h2>Income and expenditure for the period</h2><table><thead><tr><th>Account</th><th>Type</th><th>Amount</th></tr></thead><tbody>@foreach($s['income_statement'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['kind'] }}</td><td>{{ number_format($row['amount_minor'], 0, '.', ',') }}</td></tr>@endforeach</tbody></table>
<h2>Investment holdings</h2><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Quantity micro-units</th><th>Cost</th><th>Carrying value</th><th>Valuation</th></tr></thead><tbody>@foreach($s['investment_register'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['quantity_micro'] }}</td><td>{{ number_format($row['cost_minor'], 0, '.', ',') }}</td><td>{{ number_format($row['carrying_value_minor'], 0, '.', ',') }}</td><td>{{ $row['valuation_date'] ?? 'Missing' }} {{ $row['valuation_stale'] ? '(stale)' : '' }}</td></tr>@endforeach</tbody></table></div>
<h2>Recorded performance</h2>@if($s['performance']['available'])<p>Period time-weighted return: {{ $s['performance']['time_weighted_return_percent'] }}%. {{ $s['performance']['method'] }}</p><p>{{ $s['performance']['valuation_basis'] }}</p>@else<p>{{ $s['performance']['reason'] }}</p>@endif
@endif
<h2>Contribution calls</h2><table><thead><tr><th>Due date</th><th>Member</th><th>Called</th><th>Paid to date</th><th>Status</th></tr></thead><tbody>@foreach($s['capital_calls'] as $row)<tr><td>{{ $row['due_date'] }}</td><td>{{ $row['member_user_id'] }}</td><td>{{ number_format($row['amount_minor'], 0, '.', ',') }}</td><td>{{ number_format($row['paid_minor'], 0, '.', ',') }}</td><td>{{ $row['status'] }}</td></tr>@endforeach</tbody></table><p>Capital calls are contribution obligations under club rules, not automatically recognised loan receivables or credit defaults.</p>
</main><footer><p>System-generated OpFin statement. Corrections create new approved entries and a new statement; this issued snapshot is not overwritten.</p><p class="hash">Content SHA-256: {{ $statement->content_hash }}</p></footer></body></html>
