// Generated by scripts/sync-brand.py. Edit brand/opfin.tokens.json.
import 'package:flutter/material.dart';

abstract final class OpFinColors {
  static const indigo = Color(0xFF353B78);
  static const indigoStrong = Color(0xFF29305F);
  static const apricot = Color(0xFFF2B38D);
  static const ivory = Color(0xFFFAF8F2);
  static const periwinkle = Color(0xFFE8EAF6);
  static const ink = Color(0xFF202436);
  static const muted = Color(0xFF555D72);
  static const line = Color(0xFFD7DAE8);
  static const white = Color(0xFFFFFFFF);
  static const success = Color(0xFF116B4E);
  static const warning = Color(0xFF865210);
  static const danger = Color(0xFFAA2636);
}
