#!/usr/bin/env python3
"""Generate brand constants from the canonical token file, or check for drift."""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def luminance(colour):
    channels = [int(colour[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return sum(a * b for a, b in zip(linear, (0.2126, 0.7152, 0.0722)))

def outputs(tokens):
    colours = tokens['colours']
    for name, value in colours.items():
        if not re.fullmatch(r'[A-Za-z][A-Za-z0-9]*', name) or not re.fullmatch(r'#[0-9A-Fa-f]{6}', value):
            raise ValueError('Invalid colour token')
    for foreground, background in [('ink', 'ivory'), ('white', 'indigo'), ('ink', 'apricot'), ('muted', 'white'), ('success', 'white'), ('warning', 'white'), ('danger', 'white')]:
        values = sorted((luminance(colours[foreground]), luminance(colours[background])))
        ratio = (values[1] + 0.05) / (values[0] + 0.05)
        if ratio < 4.5:
            raise ValueError(f'{foreground}/{background} contrast {ratio:.2f} is below 4.5:1')
    css = '/* Generated by scripts/sync-brand.py. Edit brand/opfin.tokens.json. */\n:root {\n'
    for name, value in colours.items():
        key = re.sub(r'([A-Z])', lambda m: '-' + m.group(1).lower(), name)
        css += f'  --opfin-{key}: {value};\n'
    css += '}\n'
    dart = "// Generated by scripts/sync-brand.py. Edit brand/opfin.tokens.json.\nimport 'package:flutter/material.dart';\n\nabstract final class OpFinColors {\n"
    for name, value in colours.items():
        dart += f'  static const {name} = Color(0xFF{value[1:].upper()});\n'
    dart += '}\n'
    return {
        ROOT / 'apps/web/src/app/brand-tokens.css': css,
        ROOT / 'apps/client/lib/brand/brand_colors.dart': dart,
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    tokens = json.loads((ROOT / 'brand/opfin.tokens.json').read_text())
    failed = []
    for path, content in outputs(tokens).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                failed.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if failed:
        print('Brand drift: ' + ', '.join(failed), file=sys.stderr)
        return 1
    print('Brand tokens and required text contrast pairs verified.' if args.check else 'Brand constants generated.')
    return 0

if __name__ == '__main__':
    sys.exit(main())
